FROM jenkins/agent:latest-jdk21

USER root

# RUN apt update -y
# RUN apt install -y python3 python3-pip python3-jinja2 -y


# RUN python3 -m pip config set global.break-system-packages true
# RUN pip3 install jinja2 jenkins-job-builder


RUN apt update -y \
    && apt install python3 python3-pip -y

RUN python3 -m pip config set global.break-system-packages true

RUN pip3 install jinja2 jenkins-job-builder